apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-stable
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 443
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-canary
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 443
      targetPort: https
